export const BreadBottom = "BreadBottom"
export const BreadTop = "BreadTop"
export const Seeds1 = "Seeds1"
export const Seeds2 = "Seeds2"
export const Meat = "Meat"
export const Cheese = "Cheese"
export const Salad = "Salad"
export const Bacon = "Bacon"